import 'package:hive_ce_flutter/hive_flutter.dart';

part 'analytics_summary.g.dart';

/// A cached summary for a given period, regenerated by AnalyticsProvider
/// whenever the user opens the Analytics screen or logs new activity, so
/// the screen has something to render instantly without recomputing from
/// the full FoodActivity box every frame.
@HiveType(typeId: 31)
class AnalyticsSummary {
  const AnalyticsSummary({
    required this.id,
    required this.ownerUserId,
    required this.periodStart,
    required this.periodEnd,
    required this.totalAdded,
    required this.totalConsumed,
    required this.totalWasted,
    required this.totalExpired,
    required this.wastePercentage,
    required this.generatedAt,
    this.mostWastedItemName,
    this.totalDonated = 0,
  });

  @HiveField(0)
  final String id;

  @HiveField(1)
  final String ownerUserId;

  @HiveField(2)
  final DateTime periodStart;

  @HiveField(3)
  final DateTime periodEnd;

  @HiveField(4)
  final double totalAdded;

  @HiveField(5)
  final double totalConsumed;

  @HiveField(6)
  final double totalWasted;

  @HiveField(7)
  final double totalExpired;

  /// wasted / added as a 0-1 fraction, guarded against divide-by-zero.
  @HiveField(8)
  final double wastePercentage;

  @HiveField(9)
  final DateTime generatedAt;

  /// Name of the food item with the highest wasted quantity in this
  /// period, derived from FoodActivity records directly (no category
  /// join, since ShoppingItem/FoodActivity don't carry categoryId).
  @HiveField(10)
  final String? mostWastedItemName;

  /// Total quantity donated in this period. Added after the initial
  /// build-out once ActivityType.donated was introduced; defaults to 0
  /// so older cached summaries without this field still deserialize fine.
  @HiveField(11)
  final double totalDonated;

  AnalyticsSummary copyWith({
    String? id,
    String? ownerUserId,
    DateTime? periodStart,
    DateTime? periodEnd,
    double? totalAdded,
    double? totalConsumed,
    double? totalWasted,
    double? totalExpired,
    double? wastePercentage,
    DateTime? generatedAt,
    String? mostWastedItemName,
    bool clearMostWastedItemName = false,
    double? totalDonated,
  }) {
    return AnalyticsSummary(
      id: id ?? this.id,
      ownerUserId: ownerUserId ?? this.ownerUserId,
      periodStart: periodStart ?? this.periodStart,
      periodEnd: periodEnd ?? this.periodEnd,
      totalAdded: totalAdded ?? this.totalAdded,
      totalConsumed: totalConsumed ?? this.totalConsumed,
      totalWasted: totalWasted ?? this.totalWasted,
      totalExpired: totalExpired ?? this.totalExpired,
      wastePercentage: wastePercentage ?? this.wastePercentage,
      generatedAt: generatedAt ?? this.generatedAt,
      mostWastedItemName: clearMostWastedItemName
          ? null
          : (mostWastedItemName ?? this.mostWastedItemName),
      totalDonated: totalDonated ?? this.totalDonated,
    );
  }
}