// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbKKntXQvUSFbTnc5zt2Es3WehkbN9a-E',
    appId: '1:793990837446:web:872f6186bc75eb7dd993c7',
    messagingSenderId: '793990837446',
    projectId: 'pantrypal-2a765',
    authDomain: 'pantrypal-2a765.firebaseapp.com',
    storageBucket: 'pantrypal-2a765.firebasestorage.app',
    measurementId: 'G-69KR6KKJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5gZNPmehaIfcFqwOiZtjLGiFQON0z8A',
    appId: '1:793990837446:android:ed2ecb35253a7063d993c7',
    messagingSenderId: '793990837446',
    projectId: 'pantrypal-2a765',
    storageBucket: 'pantrypal-2a765.firebasestorage.app',
  );
}
