// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_application_final_project/models/app_settings.dart';
import 'package:flutter_application_final_project/models/food_category.dart';
import 'package:flutter_application_final_project/models/food_item.dart';
import 'package:flutter_application_final_project/models/shopping_item.dart';
import 'package:flutter_application_final_project/models/storage_location.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(FoodCategoryAdapter());
    registerAdapter(FoodItemAdapter());
    registerAdapter(ShoppingItemAdapter());
    registerAdapter(StorageLocationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(FoodCategoryAdapter());
    registerAdapter(FoodItemAdapter());
    registerAdapter(ShoppingItemAdapter());
    registerAdapter(StorageLocationAdapter());
  }
}
