// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_application_final_project/models/food_category.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FoodCategoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FoodCategoryAdapter());
  }
}
